### PR TITLE
Enemy letter categories

### PR DESCRIPTION
**Pull request by AndySky21**
Changed letters for enemies according to issue.
Note:

1. Vigilantes do quite some damage, and I marked them with an S as soldiers (they defend their territory, after all)
2. Lizards, both single and in packs, and swarms of rats are marked as B. I know there's no issue with their former letters (L and R), but I thought a "rule" was necessary. Note that the "giant lizard" is marked as F, not B, the letter I used for "anomalous" creatures. Tell me if you mean something more "normal".
3. Deformed figure is deformed. I know that it drops steel and cloth, but I can't convince myself that it is human any longer. So F.
4. Not wishing to break "my" rules, I marked the chief of men defending the coal mine as S. It's the same situation of Vigilante, he defends his place. Well, he defended, actually.
5. What is a Beastly Matriarch? I suppose it's an F... a mutated creature?

Other corrections:

1. There's no way the veteran in the Ruined City, armed with a bayonet, causes the same damage of thugs and less than birds, as the Bayonet is the strongest weapon of the game. I raised his damage to 6, less than the veteran in Sulphur mine (d. 10) though.
2. Tabulation fix in Setpieces.

### CODE REVIEW

**Comment by AndySky21** [comment]
However, there's something I'm not satisfacted with. Some letters are the same of landmarks, even if there's no affinity between beasts and boreholes.
I'd like to change B, F, S and M (practically all) to assign them unused letters. Whaddaya think?

**Comment by Continuities** [comment]
I'm cool with it.

**Comment by AndySky21** [comment]
Yay!
@Continuities after this I will pause for a whole week! Think! 7 days without "AndySky21 wants to merge". Who knows if you will use this time to review my stuff? (superlol)

**Comment by skj3gg** [comment]
I'm speaking at a conference tomorrow so swamped now. Then I'm sprinting ADR next week. So when you come back it will be best to get a fresh start off of master. 




I can't say thank you enough for your work!

**Comment by AndySky21** [comment]
One day I will make a list of how many things I have to be thankful to this project for.
Ok then, I'll end up the stuff I'm working on, and in some days I will discuss it with You!

**Comment by Continuities** [comment]
Yeah, I can't possibly keep up with you. Between my day job and my other
projects, there's very little time left to review ADR PRs. I'll try to set
some time aside this weekend and see how many I can get through.

**Comment by AndySky21** [comment]
These new letters are not in the landmark list.
R wild animals (beast, birds, lizards, rats)
T mutated creatures (includes giant lizards)
E human enemies (old men, scavengers, thugs and squatters)
D armed human enemies (includes vigilantes, soldiers, snipers, commandos, veterans and chiefs)

**Comment by skj3gg** [comment]
f219b32. WOOTZ!

**Pull request closed without merging**
