### PR TITLE
Set heal

### PR DESCRIPTION
**Pull request by AndySky21**
Enables/disables eatMeat and useMeds buttons according to player's HP.
The check is done on panel creation, after attacks and after healings.
Also create separate groups for attack buttons, healing buttons, leave buttons. 

#460 again.

### CODE REVIEW

**Comment by AndySky21** [comment]
Just a moment for last minute improvements

**Comment by AndySky21** [comment]
Now it's good for tests. It's limited to the correct changes (healing check and buttons grouping).

**Comment by vankasteelj** [comment]
Great job, the interface in combat is way better now. 

There's an issue though, the buttons don't go "inactive" anymore. Let's say I have 1 med, I go for a walk, get into a fight with some sad old men that had the misfortune of crossing me, and I use my (only) med. Once the 'take med cooldown' is over, the button used to remain greyed, because I have no med left. But here, the button resets to 'clickable', although I don't have med, and I can click it, triggering the cooldown, but it doesn't heal me (as I didn't have a med to start with)

**Comment by AndySky21** [comment]
Yes I know it. That will be fixed in the update I mentioned in another
issue.
Thank you so much for the review! :)

**Pull request merged**
