### PR TITLE
Update strings.po

### PR DESCRIPTION
**Pull request by HuXTUS**

### CODE REVIEW

**Comment by groteworld** [comment]
Could I ask @SnoUweR @Anwinz @lucky-ly or @codeskull to look over these changes? Sorry, I don't know Russian.

**Comment by HuXTUS** [comment]
Of course. )

**Comment by HuXTUS** [comment]
Hello, Is there anyone alive?

**Comment by Continuities** [comment]
I can try to look at it in the next few months. Life's busy as hell.

**Comment by gitupofftheflooranddosomework** [comment]
close and can be resolved going forward as translators are available for new strings

**Pull request closed without merging**
