### PR TITLE
update french localization

### PR DESCRIPTION
**Pull request by vankasteelj**
this commit contains updated strings in po & js for French

- updated po from pot
- localized new strings
- corrected some existing translations
- generated js file
- translate hardcoded css
- widen tooltips & hullrows & workers (fr only)

### CODE REVIEW

**Comment by vankasteelj** [comment]
armghqqzjehqzjeh

not to merge, there still are errors

**Comment by vankasteelj** [comment]
not to merge, there still are errors I only see now I'm reviewing on gh

**Comment by vankasteelj** [comment]
ready :)

**Comment by vankasteelj** [comment]
@Continuities I'd like to remove my fork :D is a merge gonna happen any time soon ?

**Comment by Continuities** [comment]
Um... maybe? Unfortunately, I don't have a lot of free time to maintain
this repository.

**Pull request closed without merging**
