### PR TITLE
Fix message typo.

### PR DESCRIPTION
**Pull request by jimt**

### CODE REVIEW

**Comment by AndySky21** [comment]
Just fixing the message in setpieces.js breaks localisation, as the line does not match with translations.

**Comment by Continuities** [comment]
Aw geez, you're absolutely right. That's what I get for merging without reading.

**Comment by jimt** [comment]
Sorry, I had assumed that there was an automated scheme that updated the message ids for the translations.  So what was the proper way?  Fix the message and all of the translations?

**Comment by AndySky21** [comment]
The files to be fixed are the POT file, PO and JS files in Lang folder.

**Pull request merged**
