### PR TITLE
added background to index and edited .menu of main.css

### PR DESCRIPTION
**Pull request by kartikeyakotnala**
added a background which reflects theme of game and added border and background to lower menu buttons also the lower menu buttons now toggle their colors according to lights on and off.

### CODE REVIEW

**Comment by Continuities** [comment]
ADR's aesthetic is strongly minimalistic. The simple black text on white is integral to its identity. This change is detrimental. Sorry.

**Comment by kartikeyakotnala** [comment]
I had also added invert color to lower menu according to lights on and off feature in .menu and .menu:Hover in main.css

**Comment by kartikeyakotnala** [comment]
It might not conflict with the main theme of black and whie

**Comment by kartikeyakotnala** [comment]
It might not conflict with the main theme of black and white

**Pull request closed without merging**
