### PR TITLE
Hyperproof cooldown state

### PR DESCRIPTION
**Pull request by AndySky21**
After updating the Hyper stuff, I fixed Cooldown state for both code readability and functionality with Hyper mode.
Buttons can now have a "state" generation param/ data_ attribute. This says to the engine that their cooldown is to be stored in state.
On load, if a state is present for suitable buttons, the cooldown starts from the stored value.
Residual cooldown is stored as "nominal" tenth of seconds, even if hyper mode is on. In that case, the script updates it in half the time (-1 every 50 milliseconds instead of 100) and the timeout starts from half the time.

### CODE REVIEW

**Comment by skj3gg** [comment]
Sorry for this late suggestion, but to save some processing power, why not just make it update every half or quarter second. I would hope people wouldn't be upset, or even notice half a second... in a cooldown... after refreshing. Thoughts?

**Comment by AndySky21** [comment]
I think there'd be nothing bad.
It could be update every half second. Quarter in case of hyper.
I have another project on the ready for saving Mysterious Wanderers' return, I'll use the same time module.
At present I'll fix this.

**Comment by AndySky21** [comment]
Done.

**Comment by AndySky21** [comment]
Done and fixed.

**Comment by AndySky21** [comment]
Short note: state is updated (every 500 milliseconds), but as it means a lot of work, it does not trigger save. Saving relies upon autosave.

Solves #351. Hey cheaters, you were relieved when you saw that the previous was closed, weren't you?

**Comment by AndySky21** [comment]
Complete bugfix. Now it's bulletproof, not only hyperproof.
Note: previous test saves could not work, due to the fact that now Cooldown state is measured in seconds.

**Comment by AndySky21** [comment]
Gameplay ease bugfix

**Comment by grotewold** [comment]
same state as #360, refreshes makes all buttons with cooldowns be cooling down.

**Comment by AndySky21** [comment]
I left a parameter unchanged from a previous commit.
It works as expected now.

**Comment by grotewold** [comment]
65d7cfd7844ee5e1372aea314fd92547a9864388

AND DONE!
superbad-jonah-hill-running-out-of-breath

**Pull request closed without merging**
