### PR TITLE
Add Galician translation

### PR DESCRIPTION
**Pull request by decrecementofeliz**

### CODE REVIEW

**Comment by ThoolooExpress** [comment]
Looks like you forgot to ignore .ds_store files, might want to get rid of that

**Comment by decrecementofeliz** [comment]
Thanks for the advise @ThoolooExpress , I'm quite new in git, but I love learning :)

**Comment by decrecementofeliz** [comment]
Thank you for the game! But I can't see the Galician language yet in http://adarkroom.doublespeakgames.com, how often do you deploy the changes? Sorry for the impatience, I just know a couple of friends that would love to play this in Galician :)

**Comment by decrecementofeliz** [comment]
Hi, any news about this? Some languages are missing in the website menu, can you check please? Thank you!

**Comment by Continuities** [comment]
I deploy changes when I have time. Apologies for the delay 😿

**Comment by decrecementofeliz** [comment]
Of course, I just wanted to check there was nothing missing in my PR, I'm quite newbie in Git. Thanks!

**Pull request merged**
