### PR TITLE
Notify events before their effect

### PR DESCRIPTION
**Pull request by AndySky21**
This fixes a little oddity: when purchasing the compass from the Nomad, it appears to point before it is judged functioning. I inverted event notification and event reward.

### CODE REVIEW

**Comment by skj3gg** [comment]
I'll have to play around with this and be sure this doesn't reverse other notifications. Please be patient, thanks!

**Comment by AndySky21** [comment]
It specifically works on items bought by the Nomad, and the only item which produces 2 notifications should be the Compass (unless you have reached storage ceiling, I guess).
Of course you have to test it! :)

**Comment by skj3gg** [comment]
Commited with fb13f6e. Thanks again!

**Comment by AndySky21** [comment]
You merge my stuff? Do you? Fine! then I'll send you more stuff to merge!
...just a joke, actually. However.
In Events, event loading should precede any other stuff (rewards and notifications), so if an event action can actively change notifications and rewards, they can be loaded only when updated.
I'll pull it below.

**Pull request closed without merging**
