### PR TITLE
Exiting World without navigating tabs

### LINKED ISSUE #358: Movement when returning from world
I often use WASD keys when moving in the world, because using arrow keys up and down it interferes with page scrolling, but I found a minor issue.
When the "returning step" in the world is made towards west, the game interprets that keypress event twice, so the map is closed and the game moves to the Outside tab.
Can it be prevented?

### PR DESCRIPTION
**Pull request by AndySky21**
A new property and a new method to disable navigation when moving to World and to restore it when coming back. Well, not exactly "when", as it the script would interpret a step left or right as "navigate to Outside/Ship", so navigation is re-enabled 100 milliseconds after disembarking/respawning.

I promised you I wouldn't post other commits, but now it's after midnight.

Just forgetting. It fixes #358.

### CODE REVIEW

**Comment by wmassingham** [comment]
I'd like to use this code in a pull request, but I don't see how tab navigation is actually disabled. Am I missing something?

**Comment by AndySky21** [comment]
You're right indeed, thanks! I missed the disabling part!!!

**Comment by AndySky21** [comment]
Done.World.js, line 921: disables tabNavigation when embarking. Engine.tabNavigation is restored when dying or returning home.

**Comment by AndySky21** [comment]
As I'm here I will also ask this. Am I the only one who finds painfully annoying that screen scrolls when using up-down arrow keys (and probably left/right too, weren't the viewport wide enough) while exploring?
I'm also working on a pause button during fights (it's done, actually) and I have associated it to the spacebar for an additional keyboard shortcut. Well, it scrolls even worse of course.
Should it be fixed somehow?

**Comment by Continuities** [comment]
The keyboard didn't scroll the viewport when I originally released it. I
vividly remember fighting with keyboard scrolling during Dusty Path and
Liftoff scenes. It totally shouldn't scroll when you move around with the
keys.

**Comment by AndySky21** [comment]
Ok then. Let this as is for now, and I'll try to put an end to vertical and horizontal scrolling while in the Barren World.

**Comment by AndySky21** [comment]
Listen to my advice and tell me if you like it.
Let's get rid of the scrollSidebar thing, it is counterintuitive and the side boxes interfere with Tab titles when one opens all the tabs. On the other hand, on a fully developed game, it would be required in Room too (I have pretty much everything and boxes touch the lower border of the window. It's true that I added stuff, but it's not important.
So let's just prevent scrolling in World and Space, while it will remain functional in Room, Outside and Path. The issue with boxes going out of sight could be fixed with collapsible boxes (I'm working on it).
Bad idea? Good idea? Am I going to get fired?

**Comment by Continuities** [comment]
Scrolling actually has to be possible on the Path, just in case people have
very short viewports. Just can't scroll with the arrow keys.

**Comment by AndySky21** [comment]
So you're for keeping scrollSidebar with arrows. Hmmm the same short viewport could give some trouble in Room then.
Ok then. Let's see what I can do.

**Comment by Continuities** [comment]
I'm not a fan of scroll bars, but they're better than players missing the
bottom of the map.

**Comment by AndySky21** [comment]
Indeed. And as of now, bottom of the map already conflicts with menu, which also conflicts with side boxes, which can conflict with tab titles.

**Comment by AndySky21** [comment]
Merged further improvements by @wmassingham

**Comment by AndySky21** [comment]
... @Continuities , do you remember if the purpose of Engine.keyLock was the same of my tabNavigation? Because in that case, it'd be better to keep just one property and I'll change mine.

**Comment by Continuities** [comment]
Engine.keyLock, I believe, exists to prevent interaction when interaction
isn't allowed (moving around the map while in an encounter, moving the
spaceship during the "crash" animation, etc...)

**Comment by AndySky21** [comment]
I see. I will adapt it to my keyboard tab navigation, so one less var.

**Comment by AndySky21** [comment]
This works now. keyLock and tabNavigation must be kept separated, as keylock rules keydown event and can be useful for button shortcuts, while tab navigation is tied to keyup and has different rules for disabling. 
About scrolling, I'd like to try a different approach. Consider that users don't easily discover about side scrolling, as it is quite slow. Also consider that a container height of 700px forces a scrollbar on some user agents, but using that scrollbar doesn't scroll sidebox.
Here's my idea. Using native scroll will scroll the sidebar and, if necessary, it will scroll page content as well (e.g. in case it's too long for viewport).
Every time a box is completely visible in the desired direction, it stops scrolling (it can be tricked with CSS): e.g. if you are scrolling down and the bottom border is visible, "stop scrolling". This will allow for a differential scroll between side and content, even if it will be a bit harder to achieve.
I'll try something while you review my previous stuff or enjoy summertime :D

**Comment by grotewold** [comment]
Woof, daf5de3973936cfa0d0fdef783962be80e7f52d1 - 358fe5fbcc00d3e10965f1540aa7d23861fdbae4.

THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU .......

**Pull request closed without merging**
