### PR TITLE
Update outside.js

### PR DESCRIPTION
**Pull request by JMRedford**
adrchange1
Changed sickness event to kill up to half of the villagers instead of up to 20.

### CODE REVIEW

**Comment by AndySky21** [comment]
I found someone who hates the player more than I do! How nice :)
Just in case the "plague" event was not bad enough.

**Comment by JMRedford** [comment]
Actually, I find medicine pretty early, usually.  This change is nicer to players with less than 40 villagers.

**Comment by WesTyler** [comment]
Despite the consequences I would inevitably face in my own game, this is a fantastic idea. I like things that make the game more responsive/immersive. Responding to population adds a neat risk/reward element to having a bunch of workers.

**Comment by skj3gg** [comment]
@WesTyler I definitely agree! Thanks you for your contribution @JMRedford

**Comment by skj3gg** [comment]
And with that we are at 500 commits! WOW, love this community! Thanks again to all!!

**Comment by JMRedford** [comment]
My first successful Github pull request.  Thanks, @WesTyler .

**Comment by JMRedford** [comment]
And thanks @skj3gg

**Comment by skj3gg** [comment]
:beer: Cheers to many more!

**Pull request merged**
