### PR TITLE
Fights box update

### PR DESCRIPTION
**Pull request by AndySky21**

### CODE REVIEW

**Comment by AndySky21** [comment]
Sorry for the mess.
This pr contains the same changes of #463 and #467, but it's meant as an improvement/fix for #466 (it introduces the start cooldown and the out-of-focus autopause). It also fixes "take" and "drop" labels, which now rely upon data-legend attribute (which is translated).
I feel the hate rising, men!

**Comment by AndySky21** [comment]
As it substitutes now-dead #466, it gangs up with other PRs below #460.

**Comment by vankasteelj** [comment]
It also destroys the combat system, because you added pause/resume and it prevents ennemy from attacking more than once.

**Comment by AndySky21** [comment]
This is a bug I don't know. I see. This will probably disappear, the update
works I hope. Thanks...
Il 18/Apr/2016 21:59, "Jean van Kasteel" <notifications@github.com> ha
scritto:

**Pull request merged**
