### PR TITLE
Keyup lock

### PR DESCRIPTION
**Pull request by AndySky21**
This is a better solution for #358. It takes into account Engine.keyLock property.
When it's true, it inhibits both keydown and keyup. If keydown was allowed (and keyLock is enabled after that, as it is the case when making "the last step", keyup will undo the lock (without triggering its action).
This should also fix what @wmassingham noticed about event panels (see #380), in a better way than the one I found before.

A final note: keyup stuff is optimizable. I will try it when I have time, so to bring closer to the side box scrolling issue.

### CODE REVIEW

**Comment by AndySky21** [comment]
Ready to merge. In case you do it, #380 is useless.

**Comment by wmassingham** [comment]
Okay, but will this conflict with future hotkeys, e.g. #11?

**Comment by AndySky21** [comment]
Indeed, my previous solution (tabNavigation, which you used too) brought no conflict with hotkeys, as far as hotkeys are bound to keyUp event instead of keyDown (keydown is disabled during events and fights, as you can see).
In order to avoid conflicts, this commit should be paired with a specific key mapping and keyboard should never be disabled (which is not nice).
Otherwise #380 should be kept, but with a fix. I'll patch that and @Continuities will tell us what's better (and whether or not hotkeys are expectable in the near future - #11 is 2 years old).

**Comment by AndySky21** [comment]
#380 "World to path" is now fixed according to how I arranged things here.
The timed method (which was inefficient) has been removed, and now it won't conflict with future hotkeys.

**Pull request closed without merging**
