### PR TITLE
No build if room is mild

### PR DESCRIPTION
**Pull request by AndySky21**
This is just an idea, I wanted to see if it can be appreciated.
In #352 it was said that, as an "idle game", ADR should not punish players if the game goes idle, and I agree (I spent a whole day playing with other, less interesting idle games to realize that. Pure personal research!)
However, a piece of unreachable code gave me an idea (I mentioned in the issue).
Builder keeps stoking the fire, thus preventing the room from becoming cold. But if the room remains mild, when asked to build something she will "just shiver" as it used to be before the fire was placed in State.

### CODE REVIEW

**Comment by skj3gg** [comment]
I feel like this still punishes the player for letting the room/game go idle, even though it's better than going cold. 

It is a little confusing that the builder has enough energy to keep stoking a fire but I ask for one trap and they become unresponsive.

**Comment by AndySky21** [comment]
The concept of make the player "pay a move" every time ADR goes idle is intriguing, but the original idea behind it is different (emotional). 
I find it sad that the player can, as a matter of fact, press the "Light fire" button only once throughout the whole game and then forget it altogether, I'd like the player has a reason to keep doing that initial action of the game as a sense of continuity.
To make a comparison, consider the game "Candy Box". The only possible action at the beginning is "eating candies". The game then moves on further and further, and the player could forget about that. But eating candies rises maximum health, so the player has a reason to remember where everything started from.

About the logic of actions, I know that a "mild" temperature could not be cold enough for the Builder to "shiver", but it could be stated that she's "too busy in keeping the fire burning to build anything" (yes, after all she cares more about health than the village improvements. Call her selfish!).

**Comment by Continuities** [comment]
I think I agree with @skj3gg on this one. Changing the build threshold from cold to mild doesn't feel like a meaningful change. Perhaps the correct solution here isn't a penalty (like currently implemented, though unreachable), but rather a bonus if the player keeps the fire higher than necessary. Maybe the workers work slightly faster, or beneficial events happen slightly more frequently, etc...

**Comment by AndySky21** [comment]
@Continuities, this is nice indeed!! :+1: for the positive events happening more often (i.e. travellers come more frequently if they see the fire burning bright)

**Pull request closed without merging**
