### PR TITLE
Change the enemy labels #377

### PR DESCRIPTION
**Pull request by svs192219**
Only some of the labels are changed as I'm not sure whether full name descriptor would look good.

### CODE REVIEW

**Comment by AndySky21** [comment]
It depends on how it fits the atmosphere of the game, as it is "minimal".
I like the short words, though. They give you the idea of what you are fighting against.
Most important for things like Scavenger and Sniper, which are different in one important aspect: while Scavenger stops attacking if tangled, Sniper keeps on shooting (of course) and as such it's important to understand how to fight.

**Comment by svs192219** [comment]
I too like the names to be short, but to handle the issue of same letter label for two different enemies rather than giving some random letter it is better to give four-five letter descriptor for the sake of understanding.

**Comment by Continuities** [comment]
The problem with using full (or partial) strings is that we're starting to get into localization territory. With a single character, the link to English is as minimal as possible. The closer we make the labels to full English words, the more jarring they'll look in an otherwise localized interface. I don't know about you, but I don't really want to have to translate all these labels into all the languages that ADR currently supports.

**Comment by AndySky21** [comment]
As I started playing ADR in english I didn't even realize that having the short words in English would be weird, that 'd be indeed.
And as the letters "move" during combat, it would also be difficult to read. Maybe a couple of letters as an acronym would be enough to improve recognition of enemies without language issues.

**Comment by Continuities** [comment]
Yeah, I think 2 (max 3) letters would be okay.

**Comment by AndySky21** [comment]
Yeah but this time I won't do that :D too many PR from me lately!

**Comment by Continuities** [comment]
Seriously! We can't keep up with you!

**Comment by AndySky21** [comment]
Haha :)
I just happened to have some spare time and I wanted to give as many contributions I could, so that you can then see if they are correct.

**Comment by youknowone** [comment]
Can I vote for 1-letter name because I like the log-like atmosphere of this game? ;)

**Comment by AndySky21** [comment]
I was reviewing some battle lately. I'd like 2 cents to @youknowone's vote.
Proposal: 1-letter names, letters similar for similar enemies.
E.g. B for wild animals, S for soldiers and snipers (enemies that shoot, maybe). M for human enemies without a military training, F for inhuman menaces larger than beasts and so on.

**Comment by Continuities** [comment]
+1

**Comment by skj3gg** [comment]
@svs192219, Your changes are embedded in #396 and I'm working on merging that so I'll close this one.
Thanks for your contribution!

**Comment by skj3gg** [comment]
8d3b313e9ca3832066790bf87b00df8fa849dad8

**Pull request closed without merging**
