### PR TITLE
Waiting for Mysterious Wanderers

### PR DESCRIPTION
**Pull request by AndySky21**
Of all the events, Mysterious Wanderers are the weirdest ones, because their reward arrives with a delay. But what happens if the game is reloaded while waiting? The wanderer is invariably lost.
This very small fix is intended to store a state value whenever a MW takes some stuff away with the intention of coming back. This state value is then removed on return, which may happen during a following reload.
The only thing I don't like is registering "delayed" events separately in order to trigger their onLoad method. If further delayed events are to be added, they must be manually "registered" in Events.delayed.
Everything else should work fine.

### CODE REVIEW

**Comment by AndySky21** [comment]
Done, and I'm quite proud of it.
Event.js has a new method for registering delayed events and handle their state.
Engine.js has Engine.setInterval as analog to Engine.setTimeout for cases when you use the cycle to let it close itself (it can now take into account time halving).
Room.js MW events have been updated to fit new Event.delayed() method.
State-manager has been updated accordingly (new property, therefore it is backward-compatible)

**Comment by skj3gg** [comment]
This includes the changes to #368. That's fine, just want to remember that for record keeping.

**Comment by AndySky21** [comment]
Removed remains from the older versions. They were useless, though.

No, it doesn't include #368, reward comes before notification as in your Master version. Actually it did before, but yesternight I fixed it (see change ced54fb).

**Comment by AndySky21** [comment]
Hyperproof (new method uses Engine.setTimeout and Engine.setInterval to speed up time flow).
Fixed possible overheating: state update every half second (250 milliseconds in Hyper mode, because timeout is always nominal in State)

**Comment by skj3gg** [comment]
Was playing new save. mysterious wanderer came and I gave 100 wood after event I grabbed `State.wait` and it said `Object {100wood: -1}`, then, after next save I refreshed and it still said `Object {100wood: -1}`. When another mysterious wanderer came around I tried to give them 100 furs and got the following errors. Any button press in this event after that produced the second error.

screen shot 2015-05-13 at 2 51 25 pm
screen shot 2015-05-13 at 2 51 36 pm

**Comment by AndySky21** [comment]
Damn MWs. That -1 is really weirdo. I'll fix it up now, I guess that's the
issue.

2015-05-13 20:55 GMT+02:00 Blake Grotewold <notifications@github.com>:

**Comment by AndySky21** [comment]
How nice, there were 2 different issues. I'll return the corrected stuff in some minutes.

**Comment by grotewold** [comment]
da0d39b

**Pull request closed without merging**
