### PR TITLE
Complete Esperanto translation 

### PR DESCRIPTION
**Pull request by djuretic**
Translation to Esperanto

### CODE REVIEW

**Comment by groteworld** [comment]
Thanks for adding this! We have a few more PRs to accept and we'll get this released! Sorry for the wait!

**Comment by djuretic** [comment]
Don't worry. Thanks!!

**Comment by djuretic** [comment]
Hi @groteworld , is there anything I can do to help in order to have a new release?

**Comment by Continuities** [comment]
I Just have to get off my lazy ass and do it. Sorry for the delay. I'll try
to remember tomorrow.

**Comment by djuretic** [comment]
Ok! I'll be waiting =)

**Comment by djuretic** [comment]
Hello @Continuities , please don't forget this update :smile:

**Pull request merged**
