### PR TITLE
Visual

### PR DESCRIPTION
**Pull request by AndySky21**
Readme languages table modified from Markdown to HTML markup in order to accommodate for a colspan heading cell (it no longer looks like an "Available" column and a "Languages" column).
Takes into account all previous changes proposed by me (Italian translation fix, Hut fire strings in POT file, Assets & Buildings sorting).

### CODE REVIEW

**Comment by AndySky21** [comment]
Ok, forget about what I said in #340 . Markdown tables MUST have a heading cell for columns.
I reverted the Readme to the Markdown version, so you can consider script changes separately.
I will try other solutions. In a separate branch, this time.

**Comment by skj3gg** [comment]
so this can be closed?

**Comment by AndySky21** [comment]
Yes, it can. I will post a different request as soon as I come up with something else.
Also, sorry for the mess.

**Comment by skj3gg** [comment]
No problem, we are all learning here. :)

**Pull request closed without merging**
