### PR TITLE
Missing lines

### PR DESCRIPTION
**Pull request by AndySky21**
All PO files have been updated from source POT.
Italian translation added for event notifications, both in PO and JS.
#460

### CODE REVIEW

**Comment by vankasteelj** [comment]
I believe you should stick to italian and not modify other langs. 

Let's say this is merged after #478, you'll invalidate all my changes
Now, if it's merged before #478, it might create merge conflict

**Comment by AndySky21** [comment]
Usually conflicts are solved before merging. I also regularly check for
update from other users, and if yours is merged before, I promise I will
change/discard this accordingly.
The fact is, when creating a brand new translation, contributors must rely
upon POT file, but in case of update not everybody does check it, many
simply refer to existing PO version, which can be outdated (like in this
case).

**Comment by vankasteelj** [comment]
Yeah, documentation update is needed, I'll write a wiki page page about it.

**Comment by vankasteelj** [comment]
https://github.com/doublespeakgames/adarkroom/wiki/Translating

**Comment by gitupofftheflooranddosomework** [comment]
close and can be resolved going forward as translators are available for new strings

**Comment by AndySky21** [comment]
Necroposting on that. My fault, these lines needed to be translated better.

**Pull request closed without merging**
