### PR TITLE
Removed background-color for config lists.

### PR DESCRIPTION
**Pull request by TwistedAkai**
Background colors for unordered list in options were set to match body.
This created a problem during and after the space game when the body and
text were inverted, but the ul was not. See Issue #432.

Tried this via Chrome's dev tools while at the affected screen in dark
theme, and it seemed to work. No further testing.

### CODE REVIEW

**Comment by Continuities** [comment]
Fix appears to work, but please just remove the offending CSS instead of commenting it out. There's no reason to keep it around.

**Comment by TwistedAkai** [comment]
Done. If preferred, I can make it into a single commit, or leave it as is.

**Comment by grotewold** [comment]
I can combine them, that's fine. thanks for your help!

**Comment by grotewold** [comment]
https://github.com/doublespeakgames/adarkroom/commit/55b5c3e1e74ba08d7f1a9179e8ca274d6f8f6cb3

Thanks again!

**Pull request closed without merging**
