### PR TITLE
Add buttons for 25 scales and 15 teeth (half a medicine)

### PR DESCRIPTION
**Pull request by keybounce**
To aid in reducing large hunting stockpiles when trading, bigger quantity buttons for the trader.

### CODE REVIEW

**Comment by gitupofftheflooranddosomework** [comment]
Seems like a pointless addition when you could easily buy them by counting and clicking the button, please close

**Comment by keybounce** [comment]
It is not pointless.

I'm not active with this game anymore, primarily because of the whole "The world map does not fit on-screen, scrolls, and is an absolute pain". Even the "outer space" section scrolls left/right.

But having to click many, many, many, **** MANY MANY TIMES*** , ruining trackpads and mouse buttons, is just not nice.

There is a user convenience factor here. If you disagree, feel free to use only single dollar bills for everything you purchase. After all, you can count out 200 of them at a store when you buy your groceries, right?


On 2018-09-19, at 9:29 PM, gitupofftheflooranddosomework <notifications@github.com> wrote:

> Seems like a pointless addition when you could easily buy them by counting and clicking the button, please close
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

---
Entertaining minecraft videos
http://YouTube.com/keybounce

**Comment by gitupofftheflooranddosomework** [comment]
Hey keybounce, nice to see someone still active here, i encourage you to come back and continue working on this, in a recent push i have fixed the last first two issues that you speak of, for the latter maybe i dont agree with the method more then anything as that method could be used for lots of things creating a lot of buttons, is there another solution you can think of? I was think about the following:


|----------------#----| [482]

This denotes a slider to adjust the value with and a text box where you see the value or manually enter if you wish, what do you think about this idea?

**Comment by keybounce** [comment]
That does sound like a good idea.

**Pull request closed without merging**
